# Generated by Django 5.2.15 on 2026-07-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamshifts', '0006_teamshifts_email_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callforteammembers',
            name='active',
            field=models.BooleanField(default=False, help_text='When enabled, the application form accepts new submissions.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='teamapplicationquestion',
            name='variant',
            field=models.CharField(choices=[('string', 'Text (one line)'), ('text', 'Multi-line text'), ('number', 'Number'), ('boolean', 'Confirmation (checkbox)'), ('date', 'Date'), ('datetime', 'Date and time'), ('url', 'URL'), ('choices', 'Radio button (choose one option)'), ('choices_dropdown', 'Dropdown (choose one option)'), ('multiple_choice', 'Checkbox (choose one or more options)'), ('country', 'Country'), ('phone', 'Phone number')], default='string', max_length=20, verbose_name='Field type'),  # noqa: E501
        ),
    ]
