# Generated by Django 5.2.15 on 2026-07-16 18:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0046_user_show_publicly_default_false"),
        ("teamshifts", "0008_alter_callforteammembers_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="callforteammembers",
            name="ask_role",
        ),
        migrations.AlterUniqueTogether(
            name="teammemberapplication",
            unique_together={("event", "user")},
        ),
        migrations.RemoveField(
            model_name="teammemberapplication",
            name="role",
        ),
    ]
