# Generated by Django 5.2.15 on 2026-07-16 18:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teamshifts", "0009_remove_role_from_application"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teamapplicationquestion",
            name="role",
        ),
    ]
