# Generated by Django 5.2.15 on 2026-07-10 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teamshifts", "0009_shift_location_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shift",
            name="capacity",
        ),
        migrations.RemoveField(
            model_name="shift",
            name="role",
        ),
        migrations.CreateModel(
            name="ShiftRoleAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("capacity", models.PositiveIntegerField(default=1, verbose_name="Capacity")),
                ("role", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="shift_assignments", to="teamshifts.teamrole")),
                ("shift", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="role_assignments", to="teamshifts.shift")),
            ],
            options={
                "verbose_name": "Shift Role Assignment",
                "verbose_name_plural": "Shift Role Assignments",
                "unique_together": {("shift", "role")},
            },
        ),
    ]
