# Generated by Django 5.2.15 on 2026-07-23 18:12

from django.conf import settings
from django.db import migrations
from django.db.models import Count


def dedupe_team_member_applications(apps, schema_editor):
    TeamMemberApplication = apps.get_model("teamshifts", "TeamMemberApplication")
    TeamApplicationAnswer = apps.get_model("teamshifts", "TeamApplicationAnswer")
    duplicates = TeamMemberApplication.objects.values("event_id", "user_id").annotate(c=Count("id")).filter(c__gt=1)
    for row in duplicates:
        qs = TeamMemberApplication.objects.filter(event_id=row["event_id"], user_id=row["user_id"]).order_by("created_at", "id")
        keep = qs.first()
        if keep is None:
            continue
        for other in qs.exclude(pk=keep.pk):
            for ans in TeamApplicationAnswer.objects.filter(application_id=other.pk):
                TeamApplicationAnswer.objects.update_or_create(
                    application_id=keep.pk,
                    question_id=ans.question_id,
                    defaults={"answer": ans.answer},
                )
            other.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0046_user_show_publicly_default_false"),
        ("teamshifts", "0010_dedupe_applications"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="callforteammembers",
            name="ask_role",
        ),
        migrations.AlterUniqueTogether(
            name="teammemberapplication",
            unique_together={("event", "user")},
        ),
        migrations.RemoveField(
            model_name="teammemberapplication",
            name="role",
        ),
    ]
