# Generated by Django 5.2.16 on 2026-07-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teamshifts", "0011_remove_role_from_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamrole",
            name="is_restricted",
            field=models.BooleanField(
                default=False,
                help_text="If checked, volunteers cannot self-claim shifts for this role. It requires manual assignment by an organizer.",
                verbose_name="Restricted role",
            ),
        ),
    ]
