# Generated by Django 5.2.16 on 2026-07-29 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teamshifts", "0014_teamrole_is_restricted"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftassignment",
            name="role",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="member_assignments", to="teamshifts.teamrole"
            ),
        ),
    ]
