# Generated by Django 6.0.7 on 2026-08-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teamshifts", "0018_cfm_shift_schedule_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammemberapplication",
            name="added_by_organizer",
            field=models.BooleanField(
                default=False,
                help_text="Whether this member was added directly by an organizer instead of applying through the public Call for Team Members.",
                verbose_name="Added by organizer",
            ),
        ),
        migrations.AlterField(
            model_name="teamshiftsemailtemplate",
            name="role",
            field=models.CharField(
                choices=[
                    ("teamshifts.application.received", "Application received"),
                    ("teamshifts.application.accepted", "Application accepted"),
                    ("teamshifts.application.rejected", "Application rejected"),
                    ("teamshifts.member.added_by_organizer", "Added as volunteer by organizer"),
                ],
                max_length=40,
            ),
        ),
    ]
