# Generated by Django 6.0.7 on 2026-09-11 12:58

import django.db.models.deletion
import i18nfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teamshifts", "0020_certificate_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamApplicationQuestionOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("answer", i18nfield.fields.I18nCharField(verbose_name="Answer")),
                ("position", models.IntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="option_records", to="teamshifts.teamapplicationquestion"),
                ),
            ],
            options={
                "verbose_name": "Application question option",
                "verbose_name_plural": "Application question options",
                "ordering": ("position", "id"),
            },
        ),
    ]
