# Generated by Django 6.0.7 on 2026-09-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamshifts', '0020_certificate_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='membercertificate',
            name='notified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the first certificate email notification. Null means no notification has been sent yet.', null=True, verbose_name='Notified at'),
        ),
        migrations.AlterField(
            model_name='teamshiftsemailtemplate',
            name='role',
            field=models.CharField(choices=[('teamshifts.application.received', 'Application received'), ('teamshifts.application.accepted', 'Application accepted'), ('teamshifts.application.rejected', 'Application rejected'), ('teamshifts.member.added_by_organizer', 'Added as volunteer by organizer'), ('teamshifts.certificate.generated', 'Certificate of participation generated')], max_length=40),
        ),
    ]
