# Generated by Django 5.2.16 on 2026-09-23 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teamshifts", "0022_membercertificate_notified_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamshiftsemailqueue",
            name="shift",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="teamshifts.shift"),
        ),
        migrations.AddField(
            model_name="teamshiftsemailqueue",
            name="shift_role",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="teamshifts.teamrole"),
        ),
        migrations.AlterField(
            model_name="teamshiftsemailtemplate",
            name="role",
            field=models.CharField(
                choices=[
                    ("teamshifts.application.received", "Application received"),
                    ("teamshifts.application.accepted", "Application accepted"),
                    ("teamshifts.application.rejected", "Application rejected"),
                    ("teamshifts.member.added_by_organizer", "Added as volunteer by organizer"),
                    ("teamshifts.shift.assigned_by_organizer", "Shift assigned by organizer"),
                    ("teamshifts.shift.claimed_by_volunteer", "Shift sign-up confirmation"),
                    ("teamshifts.voucher.sent", "Voucher sent to volunteer"),
                    ("teamshifts.certificate.generated", "Certificate of participation generated"),
                ],
                max_length=40,
            ),
        ),
    ]
