# Generated by Django 5.2.16 on 2026-10-03 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
        ("teamshifts", "0023_shiftlocation_linked_room"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamshiftsemailtemplate",
            name="role",
            field=models.CharField(
                choices=[
                    ("teamshifts.application.received", "Application received"),
                    ("teamshifts.application.accepted", "Application accepted"),
                    ("teamshifts.application.rejected", "Application rejected"),
                    ("teamshifts.member.added_by_organizer", "Added as volunteer by organizer"),
                    ("teamshifts.voucher.sent", "Voucher sent to volunteer"),
                    ("teamshifts.certificate.generated", "Certificate of participation generated"),
                    ("teamshifts.shift.reminder", "Shift reminder (24 hours before)"),
                ],
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="ShiftReminder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day", models.DateField(help_text="Event-local date of the shifts this reminder covered.")),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="teamshifts_shift_reminders", to="base.event")),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="teamshifts_shift_reminders", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Shift reminder",
                "verbose_name_plural": "Shift reminders",
                "unique_together": {("event", "user", "day")},
            },
        ),
    ]
