from django.urls import path
from eventyay.common.urls import OrganizerSlugConverter  # noqa: F401

from . import views

event_patterns = [
    path(
        "teamshifts/apply/",
        views.PublicApplyView.as_view(),
        name="apply",
    ),
    path(
        "teamshifts/apply/thanks/",
        views.PublicApplyThanksView.as_view(),
        name="apply_thanks",
    ),
    path(
        "teamshifts/apply/s/<str:secret>/",
        views.PublicApplySecretView.as_view(),
        name="apply_secret",
    ),
    path(
        "teamshifts/shifts/",
        views.PublicShiftScheduleView.as_view(),
        name="public_shift_schedule",
    ),
    path(
        "teamshifts/shifts/api/",
        views.PublicShiftScheduleAPIView.as_view(),
        name="public_shift_schedule_api",
    ),
    path(
        "teamshifts/shifts/<int:pk>/",
        views.ShiftDetailView.as_view(),
        name="public_shift_detail",
    ),
    path(
        "teamshifts/shifts/<int:pk>/claim/",
        views.ShiftClaimView.as_view(),
        name="public_shift_claim",
    ),
    path(
        "teamshifts/shifts/<int:pk>/withdraw/",
        views.ShiftWithdrawView.as_view(),
        name="public_shift_withdraw",
    ),
]

urlpatterns = [
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/",
        views.TeamShiftsDashboard.as_view(),
        name="dashboard",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/settings/",
        views.CFMSettingsView.as_view(),
        name="cfm_settings",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/settings/preview/",
        views.CFMDescriptionPreviewView.as_view(),
        name="cfm_description_preview",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/richtext-preview/",
        views.RichTextPreviewView.as_view(),
        name="richtext_preview",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/settings/application-form/",
        views.CFMApplicationFormView.as_view(),
        name="cfm_application_form",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/roles/",
        views.TeamRoleListView.as_view(),
        name="roles",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/roles/<int:pk>/delete/",
        views.TeamRoleDeleteView.as_view(),
        name="role_delete",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/roles/<int:pk>/edit/",
        views.TeamRoleEditView.as_view(),
        name="role_edit",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/locations/",
        views.ShiftLocationListView.as_view(),
        name="locations",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/locations/add/",
        views.ShiftLocationCreateView.as_view(),
        name="location_create",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/locations/<int:pk>/edit/",
        views.ShiftLocationUpdateView.as_view(),
        name="location_edit",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/locations/<int:pk>/delete/",
        views.ShiftLocationDeleteView.as_view(),
        name="location_delete",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/shifts/",
        views.ShiftListView.as_view(),
        name="shifts",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/shifts/add/",
        views.ShiftCreateView.as_view(),
        name="shift_create",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/shifts/<int:pk>/edit/",
        views.ShiftUpdateView.as_view(),
        name="shift_edit",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/shifts/<int:pk>/delete/",
        views.ShiftDeleteView.as_view(),
        name="shift_delete",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/settings/questions/new/",
        views.QuestionEditView.as_view(),
        name="question_create",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/settings/questions/reorder/",
        views.QuestionReorderView.as_view(),
        name="question_reorder",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/settings/application-form/<int:pk>/toggle/",
        views.QuestionToggleView.as_view(),
        name="question_toggle",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/settings/questions/<int:pk>/edit/",
        views.QuestionEditView.as_view(),
        name="question_edit",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/settings/questions/<int:pk>/delete/",
        views.QuestionDeleteView.as_view(),
        name="question_delete",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/applications/",
        views.ApplicationListView.as_view(),
        name="applications",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/members/",
        views.MembersListView.as_view(),
        name="members",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/members/add/",
        views.MemberCreateView.as_view(),
        name="member_add",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/members/<int:pk>/toggle-arrived/",
        views.MemberArrivedToggleView.as_view(),
        name="member_toggle_arrived",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/members/send-vouchers/",
        views.BulkSendVouchersView.as_view(),
        name="bulk_send_vouchers",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/voucher-settings/",
        views.VoucherSettingsView.as_view(),
        name="voucher_settings",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/emails/templates/",
        views.EmailTemplateListView.as_view(),
        name="email_templates",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/emails/templates/preview/",
        views.EmailTemplatePreviewView.as_view(),
        name="email_template_preview",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/emails/templates/<str:role>/edit/",
        views.EmailTemplateEditView.as_view(),
        name="email_template_edit",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/emails/templates/custom/add/",
        views.CustomEmailTemplateCreateView.as_view(),
        name="custom_email_template_create",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/emails/templates/custom/<int:pk>/delete/",
        views.CustomEmailTemplateDeleteView.as_view(),
        name="custom_email_template_delete",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/applications/<int:pk>/status/",
        views.ApplicationStatusView.as_view(),
        name="application_status",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/emails/compose/",
        views.EmailComposeView.as_view(),
        name="email_compose",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/emails/outbox/",
        views.EmailOutboxView.as_view(),
        name="email_outbox",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/emails/sent/",
        views.EmailSentView.as_view(),
        name="email_sent",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/emails/<int:pk>/edit/",
        views.EmailQueueEditView.as_view(),
        name="email_edit",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/emails/<int:pk>/delete/",
        views.EmailQueueDeleteView.as_view(),
        name="email_delete",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/schedule/api/shifts/",
        views.ShiftScheduleTalksAPIView.as_view(),
        name="api_shifts",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/schedule/api/shifts/<int:pk>/",
        views.ShiftScheduleTalkAPIView.as_view(),
        name="api_shift_detail",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/schedule/api/members/",
        views.ShiftScheduleMembersAPIView.as_view(),
        name="api_members",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/schedule/api/assignments/",
        views.ShiftScheduleAssignmentsAPIView.as_view(),
        name="api_assignments",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/schedule/api/availabilities/",
        views.ShiftScheduleAvailabilitiesAPIView.as_view(),
        name="api_availabilities",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/schedule/api/warnings/",
        views.ShiftScheduleWarningsAPIView.as_view(),
        name="api_warnings",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/schedule/grid/",
        views.ShiftScheduleGridEditorView.as_view(),
        name="schedule_grid",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/schedule/toggle-publish/",
        views.ShiftScheduleTogglePublishView.as_view(),
        name="schedule_toggle_publish",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/emails/<int:pk>/send/",
        views.EmailQueueSendNowView.as_view(),
        name="email_send_now",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/applications/bulk-action/",
        views.BulkApplicationStatusView.as_view(),
        name="application_bulk_action",
    ),
    path(
        "teamshifts/event/<orgslug:organizer>/<slug:event>/applications/<int:pk>/",
        views.ApplicationDetailView.as_view(),
        name="application_detail",
    ),
]
